### ISSUE TITLE
Cannot run jasmine via `./node_modules/.bin/jasmine`

### ISSUE THREAD

**Issue by nertzy** [jasmine/jasmine-npm#15]
I'm unable to run jasmine via `./node_modules/.bin/jasmine`. This used to work in the past.

I get the following error:
```
$ ./node_modules/.bin/jasmine

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/command.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/node_modules/.bin/jasmine:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I'm on jasmine 2.1.1 Here's the relevant partial output of `npm ls`
```
├─┬ jasmine@2.1.1
│ ├─┬ glob@3.2.11
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.3.0
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ └── jasmine-core@2.1.3
```

**Comment by amavisca** [comment]
The node_modules/.bin/jasmine should just be a symlink to node_modules/jasmine/bin/jasmine - does your symlink still point there? I'm not in front of a machine that I can test this with right now, I'll check it out tonight.

**Comment by amavisca** [comment]
@nertzy I checked this out and wasn't able to reproduce it. Are you still having this issue?

**Comment by amavisca** [comment]
Sounds like the issue wasn't with jasmine itself, so I'm going to close this. If you're still having issues you can reopen the ticket.
