### ISSUE TITLE
Will not run all files and crashes on final spec

### ISSUE THREAD

**Issue by Verexa** [jasmine/jasmine-npm#39]
Operating System: Mac OS X 10.10 (Yosemite)
Jasmine Version: 2.2.1
Problem:
When running my specs, which I have compiled from Cofeescript in to Javascript, I always seem to get this error for my final spec, if I disable it `xit` then it completes fine but does not run the other files in my spec directory. I don't use spies at all in my code so this error has me stumped.

    Warning: Command failed: 
    TypeError: Cannot read property 'spies' of undefined
        at Env.j$.SpyRegistry.currentSpies (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:656:53)
        at SpyRegistry.clearSpies (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1870:19)
        at Env.clearResourcesForRunnable (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:532:21)
        at Suite.j$.Suite.resultCallback (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:676:13)
        at complete (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2051:12)
        at QueueRunner.clearStack (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:594:9)
        at QueueRunner.run (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1736:12)
        at /usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1753:16
        at /usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1697:9
        at complete (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:358:9)
     Use --force to continue.

**Comment by Verexa** [comment]
I have discovered that the problem was with using [fat-arrow][1] coffeescript and binding to this.
Why would this be an issue in jasmine-npm and not [jasmine-node][2]?

[1]: http://coffeescript.org/#fat-arrow
[2]: https://github.com/mhevery/jasmine-node

**Comment by slackersoft** [comment]
To my knowledge jasmine-node is 1.3 only, and only had experimental 2.0 support. Jasmine-npm is 2.0 only, so it's possible this is a 1.3 -> 2.0 change and not a jasmine-node -> jasmine-npm change that causing the issue.

I haven't been able to reproduce the issue you're seeing though. With a very simple coffee spec

````coffeescript
it 'foo', () => 
  expect('foo').toEqual('foo')
````

The jasmine command runs fine after compiling it to javascript. I also tried adding more specs and using the `done` callback to make it async and everything seems to be running just fine. Can you get a very simple sample that reproduces the issue so we can take a look?

Thanks for using jasmine!

**Comment by Verexa** [comment]
This is an issue I can't even seem to reproduce after rewriting my specs to use the fat-arrow.
This can be closed for now and if I find it to happen again I'll let you know!
