### ISSUE TITLE
Can't run jasmine

### ISSUE THREAD

**Issue by rianby64** [jasmine/jasmine-npm#60]
After installing the last version (2.4.0) under npm -v => 3.3.6 and node -v => v5.0.0 I tried to run jasmine and got errors.

1) npm install jasmine
2) ./node/.bin/jasmine init
3) ./node/.bin/jasmine

Error
```javascript
./node_modules/.bin/jasmine
module.js:443
    throw err;
    ^

SyntaxError: /home/rianby64/Testing/demo/spec/support/jasmine.json: Unexpected token /
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:440:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Jasmine.loadConfigFile (/home/rianby64/Testing/demo/node_modules/jasmine/lib/jasmine.js:83:16)
    at runJasmine (/home/rianby64/Testing/demo/node_modules/jasmine/lib/command.js:92:11)
    at Command.run (/home/rianby64/Testing/demo/node_modules/jasmine/lib/command.js:49:7)
    at Object.<anonymous> (/home/rianby64/Testing/demo/node_modules/jasmine/bin/jasmine.js:11:9)
```

If run jasmine examples I got error too

```javascript
./node_modules/.bin/jasmine examples
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/rianby64/Testing/demo/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/example/node_example/spec/helpers/jasmine_examples'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at copyFiles (/home/rianby64/Testing/demo/node_modules/jasmine/lib/command.js:186:24)
    at Object.installExamples [as action] (/home/rianby64/Testing/demo/node_modules/jasmine/lib/command.js:127:3)
    at Command.run (/home/rianby64/Testing/demo/node_modules/jasmine/lib/command.js:47:20)
    at Object.<anonymous> (/home/rianby64/Testing/demo/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

Thanks in advance

**Comment by corporatepiyush** [comment]
jasmine.json created by command "jasmine init" is buggier. try this

{
  "spec_dir": "spec",

  "spec_files": [
    "**/*[sS]pec.js"
  ],

  "helpers": [
    "helpers/**/*.js"
  ],

  "stopSpecOnExpectationFailure": false,

  "random": false
}

**Comment by rianby64** [comment]
Thanks a lot! works! ))
So, comments shouldn't be included and the last two attributes should be quoted...

**Comment by amavisca** [comment]
Thanks for finding this. I'll fix this up tonight and get a patch release out if someone else doesn't get to it first.

Feel free to send a PR with the corrected JSON file if you'd like!

**Comment by slackersoft** [comment]
That'll teach me to get cute and comment the config file

**Comment by slackersoft** [comment]
Fix is available in 2.4.1

**Comment by jzinn** [comment]
The error running `./node_modules/.bin/jasmine examples` is still there in 2.4.1.  I had to install Jasmine globally and use the global `jasmine examples` command to get it to work.

**Comment by slackersoft** [comment]
@jzinn do you have a `jasmine.json` file that still has comments in it? The errors from this issue were caused by this. If not, what errors are you seeing?

**Comment by jzinn** [comment]
```
$ tree -I node_modules
.
├── lib
│   └── jasmine_examples
│       ├── Player.js
│       └── Song.js
├── package.json
└── spec
    ├── helpers
    │   └── jasmine_examples
    │       └── SpecHelper.js
    ├── jasmine_examples
    │   └── PlayerSpec.js
    └── support
        └── jasmine.json

7 directories, 6 files
```

```
$ cat package.json 
{
  "name": "jasmine-test-project",
  "version": "1.0.0",
  "description": ".",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jasmine": "^2.4.1"
  }
}
```

```
$ npm list
jasmine-test-project@1.0.0 /path/to/jasmine-test-project
└─┬ jasmine@2.4.1
  ├── exit@0.1.2
  ├─┬ glob@3.2.11
  │ ├── inherits@2.0.1
  │ └─┬ minimatch@0.3.0
  │   ├── lru-cache@2.7.3
  │   └── sigmund@1.0.1
  └── jasmine-core@2.4.1
```

```
$ cat spec/support/jasmine.json 
{
  "spec_dir": "spec",
  "spec_files": [
    "*/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/*/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

```
$ npm uninstall -g jasmine
- exit@0.1.2 node_modules/jasmine/node_modules/exit
- inherits@2.0.1 node_modules/jasmine/node_modules/inherits
- jasmine-core@2.4.1 node_modules/jasmine/node_modules/jasmine-core
- lru-cache@2.7.3 node_modules/jasmine/node_modules/lru-cache
- sigmund@1.0.1 node_modules/jasmine/node_modules/sigmund
- minimatch@0.3.0 node_modules/jasmine/node_modules/minimatch
- glob@3.2.11 node_modules/jasmine/node_modules/glob
- jasmine@2.4.1 node_modules/jasmine
```

```
$ ./node_modules/.bin/jasmine examples
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/path/to/jasmine-test-project/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/example/node_example/spec/helpers/jasmine_examples'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at copyFiles (/path/to/jasmine-test-project/node_modules/jasmine/lib/command.js:186:24)
    at Object.installExamples [as action] (/path/to/jasmine-test-project/node_modules/jasmine/lib/command.js:127:3)
    at Command.run (/path/to/jasmine-test-project/node_modules/jasmine/lib/command.js:47:20)
    at Object.<anonymous> (/path/to/jasmine-test-project/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by mbaer3000** [comment]
I have the same issue as jzinn does. The process described in http://jasmine.github.io/2.4/node.html only works when installing jasmine globally.

**Comment by amavisca** [comment]
@mbaer3000 You're right, the current npm release does still have this problem. It was fixed in this commit which hasn't been cut into a release yet: https://github.com/jasmine/jasmine-npm/commit/073e3a78fd29fd3409d88518968da8aae5f24c37

@slackersoft I can't cut the top of jasmine-npm as an npm release since it's using `provideFallbackReporter`, which isn't released on npm for jasmine-core yet. I think jasmine-npm should only rely on jasmine-core npm releases to avoid these hiccups in the future as they've come up a few times. We can cut a jasmine-npm release from where this commit landed without any issues as it only contains this fix and running our tests randomly - should I do that or wait for a core release?

**Comment by sanderboom** [comment]
> The process described in http://jasmine.github.io/2.4/node.html only works when installing jasmine globally.

Still the case :-/

**Comment by sharedgithub** [comment]
if you are trying to run jasmine test from console..(although it says console reporter is deprecated)...and if you still want to run the test using "jasmine" command from console. after "jasmine init" and "jasmine examples" paste "console_reporter.js" from this link "https://github.com/jasmine/jasmine-npm/tree/master/spec/helpers" in helpers folder within spec folder and then run "jasmine" command in console. I do not find any issue with jasmine.json file when running using this method

**Comment by ValeriiVasin** [comment]
actually i havent seen any output about console reporter etc. Not sure why. But if it is like you described and some changes are needed in order to run jasmine specs - it is breaking change that everyone who having `^2.4.1` in their package.json will get.

**Comment by slackersoft** [comment]
We've release 2.5.0 (which has some regressions) and now a patched 2.5.1 which should have this fix in it.

**Comment by ankitrg** [comment]
I am on `jasmine@2.5.3` still the same problem.

I installed jasmine as my dev dependency, now jasmine init returns 
`No command 'jasmine' found,...`

**Comment by slackersoft** [comment]
@ankitrg that is a node.js/npm thing. If you have Jasmine installed globally, it will be available without the `node_modules` prefix, but as long as it is only installed in the project it won't.

**Comment by JohnnyFun** [comment]
The detailed docs provide the correct command to run, which allows you to run it if it's not installed globally: `node node_modules/jasmine/bin/jasmine init`

https://jasmine.github.io/setup/nodejs.html

But their getting started docs still reference the broken command: `./node_modules/.bin/jasmine init`

**Comment by fbiville** [comment]
It's still broken for me with Jasmine `3.4.0`:
```
➜  yarn add -D jasmine
yarn add v1.17.3
[1/5] 🔍  Resolving packages...
[2/5] 🚚  Fetching packages...
[3/5] 🔗  Linking dependencies...
[4/5] 🔨  Building fresh packages...
[5/5] ♻️  Cleaning modules...
success Saved 1 new dependency.
info Direct dependencies
└─ jasmine@3.4.0
info All dependencies
└─ jasmine@3.4.0
✨  Done in 2.50s.
➜  node node_modules/jasmine/bin/jasmine init
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, open '[...]/node_modules/jasmine/lib/examples/jasmine.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at Object.initJasmine [as action] ([...]/node_modules/jasmine/lib/command.js:166:69)
    at Command.run ([...]/node_modules/jasmine/lib/command.js:47:20)
    at Object.<anonymous> ([...]/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '[...]/node_modules/jasmine/lib/examples/jasmine.json'
}
```

**Comment by corporatepiyush** [comment]
There should be a jasmine test to test that jasmine itself is working correctly :)
